# Generated by Django 5.1.3 on 2025-01-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0036_alter_baptism_place_of_baptism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='place_of_baptism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baptism.parishdetails'),
        ),
    ]
