# Generated by Django 5.1.4 on 2025-01-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0037_alter_baptism_place_of_baptism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_code', models.CharField(max_length=6, unique=True)),
                ('child_name', models.CharField(max_length=255)),
                ('certificate_date', models.DateField()),
                ('parish_name', models.CharField(max_length=255)),
            ],
        ),
    ]
