# Generated by Django 5.1.4 on 2025-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0038_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
