# Generated by Django 5.1.4 on 2025-03-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0041_certificate_qr_code_certificate_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='parish_id',
        ),
        migrations.AddField(
            model_name='logindetails',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baptism.parishdetails'),
        ),
    ]
