# Generated by Django 5.1.4 on 2025-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0042_remove_logindetails_parish_id_logindetails_parish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
