# Generated by Django 5.1.4 on 2025-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0043_alter_baptism_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='remark',
            field=models.CharField(default='Nil', max_length=255, null=True),
        ),
    ]
