# Generated by Django 5.1.4 on 2025-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptism', '0044_alter_baptism_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='device_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
